# -*- coding: utf-8 -*-

adoracion = {
    'C': [
        "Acude Señor junto a mi",
        "Alguien necesita aquí de ti",
        "Amor, amor de Dios",
        "Damos honor a Ti",
        "Dios está aquí",
        "Dulce refugio",
        "En momentos así",
        "Gracias por tus favores",
        "Hay momentos en que palabras no alcanzan",
        "Hay momentos tan especiales",
        "Hay poder en el nombre de Jesús",
        "Hay una necesidad",
        "Hay una presencia muy sublime",
        "La gloria es para ti",
        "Me ha tocado",
        "No daré mi vida a nadie más",
        "No existen más motivos",
        "No por obras",
        "Oh Señor yo vengo a Ti",
        "Por su amor",
        "Porque tú eres bueno",
        "Que mi vida entera esté",
        "Rendido",
        "Renuévame",
        "Señor capacítame",
        "Sin santidad nadie verá al Señor",
        "Sin tu amor",
        "Te alabo hoy",
        "Te damos gracias por la sangre del pacto",
        "Todos los días de mi vida",
        "Tu fidelidad",
        "Úsame",
        "Vengo a ti hoy Señor",
        "Vengo hoy a postrarme",
        "Venimos ante ti Señor, con corazones sinceros",
        "Yo sé que Cristo siempre me ayudará"
    ],
    'D': [
        "A ti el alfa y la omega",
        "Abre mis ojos",
        "Al que debo yo servir",
        "Al Rey de los siglos",
        "Ayúdame a mirar con tus ojos",
        "Cruzando el valle voy",
        "De gloria en gloria",
        "Dicen que no existes",
        "Divino compañero del camino",
        "El es mi paz",
        "En Ti confía mi corazón",
        "En tus manos Señor",
        "Eres el más hermoso",
        "Es hora de alabar a Dios",
        "Fue clavado en la cruz por mi",
        "Hay un anhelo",
        "Haz de mi instrumento",
        "He llegado a este lugar",
        "Hemos venido a este lugar",
        "La victoria está en Jesús",
        "Levanto mis manos",
        "Más que nunca",
        "Mira el cordero de Dios",
        "No basta solo con cantar",
        "No hay nada mejor",
        "Oh yo sigo amándole",
        "Puedo confiar en el Señor",
        "Quiero cantar una linda canción",
        "Santo, Santo es el Señor",
        "Santo, santo, santo",
        "Señor quien entrará",
        "Somos una familia en Dios",
        "Te daré lo mejor",
        "Te pido la paz",
        "Unidos",
        "Usa mi vida",
        "Venimos ante ti Señor, para adorarte",
        "Vive Jehová y bendita sea mi roca",
        "Yo quiero ser",
        "Yo quiero alabarte",
        "Yo quiero más"
    ],
    'E': [
        "Adorad al cordero Santo",
        "Aunque mis ojos no te puedan ver",
        "Bendeciré al Señor",
        "El espíritu de Dios está en este lugar",
        "En ti confía mi corazón",
        "En tus manos Señor",
        "Es más que una canción",
        "Hacemos hoy ante tu altar",
        "Hay momentos que no deberían terminar",
        "Hay un canto de alabanza",
        "Heme aquí",
        "Hombres de valor",
        "Mi anhelo es buscar de día y noche",
        "Mi pensamiento eres tu Señor",
        "Pecador ven a Cristo Jesús",
        "Que seas mi universo",
        "Quiero entregarte mis sueños",
        "Seguiré adelante",
        "Señor quien entrará",
        "Si tú hablas con Dios",
        "Soberano Dios",
        "Te vengo a decir",
        "Tu nombre",
        "Ven Espíritu ven",
        "Vine a adorarte"
    ],
    'F': [
        "Cerca de ti",
        "Con mi fe",
        "Con mis manos levantadas",
        "Conozco que todo lo puedes",
        "Delante de tu trono",
        "Enciende una luz",
        "Esperar en Ti",
        "Gracias Señor por el día tan lindo de hoy",
        "Hay una unción",
        "Jesús mi fiel amigo",
        "Paz en la tormenta",
        "Puedo sentir que estas aquí",
        "Que sería de mi",
        "Quiero escuchar tu dulce voz",
        "Señor hoy estamos ante ti",
        "Señor yo quiero construir",
        "Sumérgeme",
        "Tal como soy Señor",
        "Temprano yo te buscaré",
        "Todo te lo debo a ti",
        "Tus ojos revelan que yo",
        "Tuya es mi alabanza",
        "Yo dependo de ti",
        "Yo quiero enamorarme más de Ti"
    ],
    'G': [
        "A solas con Dios",
        "A ti atribuimos",
        "Al estar en la presencia",
        "Aprendí a vivir a soñar a reír",
        "Aquí estoy",
        "Cerca de Ti yo quiero estar",
        "Como el siervo busca por las aguas",
        "Dame un nuevo corazón",
        "Dios manda lluvia",
        "El himno de victoria",
        "El Señor es mi pastor",
        "En mi corazón hay una canción",
        "Escóndete en la mano del Señor",
        "Exaltado sea Dios",
        "Hasta aquí tu has llegado",
        "Hay una fuente en mi",
        "Hoy levantamos nuestras manos",
        "Hoy nos hemos reunido",
        "Jesús tu eres",
        "Misericordia es la que clamo a Ti",
        "Muéstrame Señor tus caminos",
        "Padre nuestro que estás en los cielos",
        "No hay problema tan grande",
        "Por un momento en tu presencia",
        "Que hermoso es ser tu hijo",
        "Quiero levantar mis manos",
        "Sendas Dios hará",
        "Siento la unción",
        "Te necesito",
        "Teniendo un mismo sentir",
        "Todavía el Señor está buscando",
        "Tu eres mi razón de ser",
        "Tus ojos revelan que yo",
        "Una ofrenda especial",
        "Vengo a ti Señor, cámbiame renuévame",
        "Yo quiero más de ti"
    ],
    'A': [
        "Santo es el Señor, Dios del universo",
        "A el alto y sublime",
        "Aquí estoy",
        "Bendito sea el Señor",
        "Cante al Señor",
        "Cuán grande es Él",
        "Digno de gloria",
        "El alfarero",
        "El poder del cristiano está en la oración",
        "El tiene toda potestad",
        "En el monte calvario",
        "Enséñame tu camino Señor",
        "Entra en la presencia",
        "Estamos reunidos hoy aquí Señor",
        "Exquisita presencia",
        "Fuerte Dios",
        "Gracias Cristo bendito",
        "Grande es tu fidelidad",
        "Junto a tus pies",
        "Las sendas de la cruz",
        "Padre mío",
        "Por la mañana yo dirijo mi alabanza",
        "Por ti soy feliz",
        "Qué bueno es el Señor",
        "Que dulce es tu presencia Oh Señor",
        "Solo con Dios encerrado estoy",
        "Toma por favor",
        "Tu amor por mi",
        "Vine a adorar a Dios"
    ],
    'B': [
        "Alaba",
        "En momentos así",
        "Engrandeced al Rey del universo",
        "Haz de mi una ofrenda",
        "La mies es mucha",
        "No hay otro Dios",
        "Rendido",
        "Tus bendiciones"
    ],
    'Cm': [
        "A ti clamé y me sanaste",
        "Agradecimiento",
        "Amémonos de corazón",
        "Cada noche que pasa",
        "Caña cascada",
        "Cristo es la peña de Horeb",
        "Desde el fondo de mi corazón te canto",
        "Dios como el incienso",
        "El Señor es mi Rey mi todo",
        "En el nombre de Dios",
        "En tu mano quiero estar Señor",
        "Jesús es digno",
        "Jesús, Jesús, Jesús es el nombre",
        "La madrugada aún estaba oscura",
        "La oración de un alma arrepentida",
        "La presencia de Dios está aquí",
        "Meditando",
        "Merecedor de alabanza",
        "Oye Israel",
        "Que te alaben los montes los valles",
        "Quiero amarte Señor"
    ],
    'Dm': [
        "Seguirte solo a ti Señor",
        "Si no hubiera sido por el Señor",
        "Sin Dios nada somos en el mundo",
        "Su nombre es Jesús",
        "Tu misericordia",
        "Unos brazos humildes se abrieron",
        "Venid a mi dice el Señor",
        "Yo sé que estás aquí"
    ],
    'Em': [
        "Abro el corazón y las ventanas",
        "Alma mía, en Dios solamente reposa",
        "Me has tomado en tus brazos",
        "No sabes tú pecador",
        "No sé porque",
        "Postrándonos ante ti Señor",
        "Señor llévame a tus atrios",
        "Te adoramos",
        "Todo es de mi Cristo",
        "Torre fuerte"
    ],
    'Am': [
        "A sus pies",
        "Deja tu fuego descender",
        "Oh Cristo mío",
        "Yo navegaré"
    ],
    'Bm': [
        "La sola presencia"
    ]
}

alabanza = {
    'C': [
        "Ama si quieres ser feliz",
        "Aquí en esta iglesia de fe y de poder",
        "Bueno es alabarte Jehová y cantar",
        "Ciento veinte estaban",
        "Con Cristo estoy contento",
        "Cuán gloriosa será la mañana",
        "Dios está aquí, qué precioso es",
        "Él es el Rey de aquí",
        "El Espíritu de Dios se mueve",
        "En mi corazón hay banderas",
        "Esta iglesia le canta y adora",
        "Hay una senda",
        "Hoy vengo a tu presencia dando gloria",
        "Jehová está en su templo",
        "La sangre de Cristo lava",
        "La sangre de Cristo lavó mi corazón",
        "Las aguas del Río del Jordán",
        "Lléname con tu Espíritu",
        "Mi alma te alaba",
        "Mirad cuán bueno",
        "¿O no sabéis?",
        "Pasa por aquí Señor",
        "Que no se apague el fuego",
        "Quién nos podrá separar",
        "Si salvo soy debo decir",
        "Somos de Él",
        "Soy bautizado",
        "Un altar encendido para Dios",
        "Vamos a alabar a Jehová con pandero",
        "Ya viene Cristo",
        "Yo me quedo con el Dios de Elías",
        "Yo quiero sentir el Espíritu de Dios",
        "Yo vivo porque Cristo vive en mí",
        "Yo vivo Señor porque Tú vives"
    ],
    'D': [
        "Abre mis ojos oh Cristo",
        "Bueno es alabarte Jehová",
        "Busca la bendición de Dios",
        "Dad y se os dará",
        "Dios mira con amor",
        "El nombre de Jesús es dulce",
        "Eres mi amigo fiel",
        "Eres tú la única razón",
        "Espíritu de Dios desciende sobre mí",
        "Fe mueve la mano de Dios",
        "Hazte tu casa sobre la roca",
        "La iglesia del Señor se tiene que mover",
        "Séllame Señor",
        "Señor eres fiel y tu misericordia eterna",
        "Soy libertado",
        "Traemos sacrificio de alabanza",
        "Tu misericordia es más grande que",
        "Yo le alabo de corazón"
    ],
    'E': [
        "Cantad a Jehová cántico nuevo",
        "Digno de gloria y de alabanza",
        "Digno eres Señor de recibir el libro",
        "El nombre de Jesús es dulce",
        "En esta reunión Cristo está",
        "En la iglesia del Señor se siente gozo",
        "Estamos de fiesta con Jesús",
        "Este culto va a estar maravilloso",
        "Gozo, gozo, gozo yo quería",
        "Hay una fiesta",
        "Honra y gloria",
        "Jacob luchó con el ángel",
        "Jesús está pasando por aquí",
        "La iglesia es tuya",
        "No hay Dios tan grande como tú",
        "Nos vamos a gozar",
        "Pueblos todos",
        "Que viva Cristo",
        "Si fueras al campo",
        "Siento que me lleno de poder",
        "Solo Dios hace al hombre feliz",
        "Soy feliz Cristo me salvó",
        "Te quiero Señor te quiero",
        "Testifiquemos",
        "Un fuego aquí, un fuego allá",
        "Venceré",
        "Yo le alabo de corazón",
        "Yo soy misionero",
        "Yo tengo un abogado",
        "Él está vivo, la tumba está vacía",
        "Esta es una fiesta, fiesta pentecostal",
        "La gloria del Señor descendió",
        "La hora de ser feliz es ahora",
        "Mi ofrenda doy",
        "Quién dijo que no",
        "Yo le alabo, yo le alabo",
        "Yo voy a andar las calles de oro con Jesús"
    ],
    'F': [
        "Ahora mismo Señor",
        "Algo está descendiendo",
        "Cuando pienso en lo lindo que es",
        "Digno eres Señor de recibir la gloria",
        "Él es el gran Yo Soy",
        "Estamos muy alegres",
        "Hay un pueblo que vive muy feliz",
        "Los salvados cantan",
        "Mirad bendecid a Jehová",
        "No hay Dios tan grande como tú",
        "Para qué pecar",
        "Si alguien te pregunta por ahí",
        "Somos el pueblo de Dios",
        "Testifiquemos",
        "Yo tengo el Cristo vivo"
    ],
    'G': [
        "Ven Espíritu divino",
        "Al Señor yo le quiero servir",
        "Alabad a Jehová",
        "Alabaré, alabaré",
        "Aquel que caminó sobre las aguas",
        "Bueno es alabar oh Señor",
        "Con gratitud",
        "Cristo es la solución de todo",
        "Cristo rompe las cadenas",
        "Cuando Cristo levante su iglesia",
        "Día a día",
        "El Cristo de poder ese es mi Cristo",
        "El Cristo que se alaba aquí",
        "Es Jesucristo Jehová la roca",
        "Estamos juntos otra vez",
        "Hay un motivo que es de grande gozo",
        "Hay una patria que Cristo ofrece",
        "Jehová está conmigo",
        "Jesucristo es real",
        "Levántate pueblo",
        "Los ídolos no tienen poder",
        "Solo hay un Dios",
        "Tu nombre levantaré",
        "Vamos por montes y collados",
        "Ven, ven, ven espíritu divino",
        "Yo siento gozo en mi alma"
    ],
    'A': [
        "Alguien está aquí",
        "Ardiendo en fuego mi alma está",
        "Como el arca de Noé sobre las aguas",
        "Cristo no está muerto",
        "Cuando Jesús caminaba",
        "Damos gracias al Señor",
        "Donde está el Espíritu de Dios",
        "El mundo necesita",
        "En el hogar, en el hogar",
        "En ese nombre hay poder",
        "Es un canto de libertad",
        "Gracias Señor por haberme traído aquí",
        "La fuente de arriba",
        "Libertad, libertad, oh qué buena",
        "Libre tú me hiciste libre",
        "Oh qué alegría llegó el pentecostés",
        "Oh Señor quiero que ardas en mi ser",
        "Quién como tú bendito Señor",
        "Quién irá, quién irá",
        "Tenemos el poder",
        "Todos juntos vamos a pedir",
        "Yo no sé a lo que tú has venido",
        "Yo sí sé, yo sí sé",
        "Yo siento paz y gozo",
        "Yo soy testigo del poder de Dios",
        "Yo tengo un Dios muy grande",
        "Yo vine a adorar a Dios"
    ],
    'B': [
        "Alguien me preguntó si Cristo iba a volver",
        "Cristo nuestro Rey está aquí",
        "Dios está aquí qué precioso es",
        "Edifiqué mi casa",
        "El Cristo de poder",
        "El Espíritu de Dios se mueve",
        "Estoy alegre, alegre muy alegre",
        "Jesús está aquí pide lo que quieras",
        "La sangre de Cristo",
        "Mi corazón y mi carne",
        "Qué bueno es Jesucristo",
        "Un milagro Dios quiere hacer en ti",
        "Ya viene, ya viene",
        "Yo tengo un Dios muy grande"
    ],
    'Cm': [
        "Aunque tenga que cruzar montes y valles",
        "Cántico nuevo",
        "Celebremos",
        "Cómo no agradecer",
        "Cuando perdido yo me hallaba",
        "Dale tu ofrenda al Señor",
        "El nombre de Jesús es poder",
        "El Señor marchando va",
        "En el cielo todos cantan aleluya",
        "Esta alabanza es",
        "Este avivamiento",
        "Hermano nunca temas ni desmayes",
        "Hoy venimos a la casa del Señor de gloria",
        "Jerusalén qué bonita eres",
        "Llorando irán los que llevan",
        "Su gloria cubrió los cielos",
        "Te amo Jehová",
        "Yo me alegré con los que me decían",
        "Yo tengo un hogar allá en el cielo"
    ],
    'Dm': [
        "Alabamos a Jehová porque Él es bueno",
        "Aquel fuego que cayó",
        "Aquí se siente la presencia de Dios",
        "Aunque otros canten",
        "Cantad a Jehová un cántico nuevo",
        "Clamando estoy",
        "Con mi Dios yo saltaré los muros",
        "Cuando el pueblo alaba a Dios",
        "Cuando los profetas clamaron a Baal",
        "El Cristo de Galilea",
        "El victorioso",
        "En el principio el Espíritu de Dios",
        "Fuego, fuego, fuego",
        "Gózate delante del Señor",
        "Hay victoria",
        "Hoy venimos a la casa del Señor de gloria",
        "Jehová es mi guerrero",
        "La alabanza a Dios",
        "Me gozaré en tu presencia Jehová",
        "Me gozaré, me alegraré",
        "Nada es imposible para Dios",
        "No hay un saludo más lindo",
        "Pandero y danza",
        "Santo, Santo tú eres",
        "Santo, Santo, Santo es el Señor",
        "Shalom Adonaí",
        "Somos más que vencedores",
        "Ven te invito a cantar al Señor",
        "Venid todos y celebrad",
        "Yo celebraré",
        "Yo he creído en un poder",
        "Yo sé que Cristo volverá muy pronto",
        "Yo sembré, Apolos regó",
        "Yo siento gozo en mi alma",
        "Aunque un ejército acampe contra mí",
        "Cantaré al Señor por siempre",
        "Cómo puedo expresar",
        "Dios es nuestro amparo",
        "Eres el rey infinito en poder",
        "Estamos reunidos todos los hijos de Dios",
        "Grande es el Señor el Rey del universo",
        "Los que esperan los que esperan",
        "Maravilloso es el Señor Jesús",
        "Qué maravilla es tener una familia",
        "Quién es el Rey",
        "Quién, quién, quién como Jehová",
        "Solamente el amor de Jesús",
        "Suena la trompeta, la iglesia está de viaje",
        "Te alabaré, te alabaré",
        "Te exaltaré",
        "Vamos a luchar contra las fuerzas del mal",
        "Vamos escalando peldaños",
        "Yo tengo el Dios"
    ],
    'Em': [
        "Aquí se canta",
        "Con mi Dios",
        "Con óleo de alegría",
        "Cuando el Señor hiciere volver",
        "Delante de tu presencia",
        "Dios no nos trajo hasta aquí",
        "Dios es nuestro amparo",
        "Dios está aquí sí",
        "El ejército de Dios marchando está",
        "El Señor está en este lugar",
        "En el altar de Dios",
        "Enviado soy de Dios",
        "Espíritu de Dios llena mi vida",
        "Estamos en la iglesia del nombre de Jesús",
        "Golpe de espada",
        "Has cambiado mi lamento en baile",
        "La fortaleza de mi vida",
        "Para ti oh Señor",
        "Pon aceite en mi lámpara Señor",
        "Pon aceite en mi vida Señor",
        "500° de poder",
        "Satúrame Señor",
        "Satúrame Señor con tu espíritu",
        "Te alabarán oh Jehová todos los reyes"
    ],
    'Fm': [
        "Aquí está el Poderoso",
        "Celebra victorioso",
        "Cuando pronuncio su nombre",
        "Es admirable, victorioso"
    ],
    'Gm': [
        "Aclamad con alegría toda la tierra",
        "Alza tus ojos y mira",
        "Cada día me siento más alegre",
        "Cuando venga de los cielos el Señor",
        "Elías oraba",
        "Jesús tú eres el amigo que me ama",
        "No hay santo como nuestro Dios",
        "Por las calles de Palestina",
        "Todo lo puedo en Cristo"
    ],
    'Am': [
        "Aunque un ejército acampe contra mí (Witt)",
        "Bajo la sombra de Pedro",
        "Cada día me siento más alegre",
        "Dios dondequiera está",
        "El poderoso de Israel",
        "En los montes, en los valles",
        "Jesucristo es tan grande",
        "La única razón de mi adoración",
        "Levántate",
        "Más que vencedor",
        "Si tuvieres fe",
        "Todo lo que respira alabe a Jehová"
    ],
    'Bm': [
        "Dios subió a su trono",
        "El día de pentecostés",
        "Grandes y maravillosas son tus obras",
        "La sola presencia",
        "Oh moradora de Sión"
    ]
}

tot_ad = sum(len(v) for v in adoracion.values())
tot_al = sum(len(v) for v in alabanza.values())

print(f"Total Coros de Adoración en PDF: {tot_ad}")
print(f"Total Coros de Alabanza en PDF: {tot_al}")
print(f"Total Coros en PDF: {tot_ad + tot_al}")
