# -*- coding: utf-8 -*-

part1_songs = [
  {
    "number": 1, "title": "LOORES DAD A CRISTO EL REY", "category": "Alabanza", "originalKey": "G", "bpm": 108,
    "lyrics": """I
LOORES DAD A CRISTO EL REY,
SUPREMA POTESTAD;
//DE SU DIVINO AMOR LA LEY,
POSTRADOS ACEPTAD//

II
VOSOTROS, HIJOS DE ISRAEL,
RESIDUO DE LA GREY;
//LOORES DAD A EMMANUEL,
Y PROCLAMADLE REY//

III
GENTILES QUE POR GRACIA DE ÉL
GOZÁIS DE LIBERTAD,
//AL QUE DE VUESTRO AJENJO Y HIEL
OS LIBRA, HOY LOAD//

IV
NACIONES TODAS, ESCUCHAD
Y OBEDECED SU LEY
//DE GRACIA Y DE SANTIDAD,
Y PROCLAMADLE REY//

V
DIOS QUIERA QUE CON LOS QUE ESTÁN
DEL TRONO EN DERREDOR,
//CANTEMOS POR LA ETERNIDAD
A CRISTO EL SALVADOR//"""
  },
  {
    "number": 2, "title": "NUESTRO IDEAL", "category": "Consagración", "originalKey": "F", "bpm": 96,
    "lyrics": """I
COMPAÑEROS NAZARENOS QUE LUCHAMOS POR JESÚS,
EN LA AMÉRICA LATINA GANANDO ALMAS PARA DIOS,
REDOBLEMOS NUESTRO ESFUERZO HACIENDO BRILLAR LA LUZ
DE PLENA SALVACIÓN.

CORO
GANARÉ A MIS COMPATRIOTAS,
GANARÉ A MIS COMPATRIOTAS,
GANARÉ A MIS COMPATRIOTAS,
EN NOMBRE DE JESÚS.

II
UN MILLÓN DE ALMAS SALVADAS ES AHORA NUESTRO IDEAL
QUE LAVADAS SEAN POR CRISTO NUESTRO GRANDE SALVADOR;
A LAS CUALES CON TERNURA GUIEMOS A LA SANTIDAD,
POR EL CONSOLADOR.

III
CADA MIEMBRO DE LA IGLESIA LUCHAR DEBE POR GANAR
A LOS POBRES PECADORES MUERTOS EN SU GRAN PECAR,
HASTA HACER QUE EL EVANGELIO LO CONOZCA MÁS Y MÁS
EL MUNDO CONTUMAZ.

IV
NAZARENOS, NAZARENAS, DIOS NOS LLAMA A COOPERAR
EN SALVAR AL MUNDO MALO POR SU GRATIS SALVACIÓN,
TRABAJEMOS CON ANHELO HASTA EL ÉXITO ALCANZAR,
POR CRISTO EL SALVADOR."""
  },
  {
    "number": 3, "title": "ALZA TU CANTO, ¡OH LENGUA MÍA!", "category": "Alabanza", "originalKey": "D", "bpm": 110,
    "lyrics": """I
AL CIELO VUELEN LOS ECOS SANTOS
QUE ARRANCO ALEGRE DE MI LAÚD;
AL CIELO VUELEN MIS DULCES CANTOS,
MIS DULCES CANTOS DE GRATITUD.

CORO
¡ALZA TU CANTO, OH LENGUA MÍA!
¡ALZA TU CANTO MI CORAZÓN!
LLÉNESE EL ALMA DE ALEGRÍA,
CON ALEGRÍA DE DEVOCIÓN.

II
YA SIENTO EL FUEGO DE LOS AMORES,
DE LOS AMORES DEL GRATO EDÉN;
YA NO ME ACOSAN AQUÍ DOLORES,
PORQUE CONTEMPLO A JERUSALÉN.

III
PADRE, EN TU REGIA, SANTA MORADA,
DONDE LA DICHA NO TIENE FIN;
ALLÍ MI PATRIA MIRO ESMALTADA
DE BELLAS FLORES DE TU JARDÍN.

IV
OH PADRE, IMPÁRTEME TU CONSUELO;
NADA EN LA TIERRA YO ESPERO YA;
Y HAZ QUE PUEDA ENTRAR AL CIELO,
QUE ALLÍ TAN SÓLO MI DICHA ESTÁ."""
  },
  {
    "number": 4, "title": "TE LOAMOS, ¡OH DIOS!", "category": "Adoración", "originalKey": "F", "bpm": 100,
    "lyrics": """I
TE LOAMOS, ¡OH DIOS!
CON UNÁNIME VOZ,
QUE EN CRISTO TU HIJO
NOS DISTE PERDÓN.

CORO
¡ALELUYA! TE ALABAMOS,
¡CUÁN GRANDE ES TU AMOR!
¡ALELUYA! TE ADORAMOS,
BENDITO SEÑOR.

II
TE LOAMOS, JESÚS,
QUIEN TU TRONO DE LUZ
HAS DEJADO POR DARNOS,
SALUD EN LA CRUZ.

III
TE DAMOS LOOR,
SANTO CONSOLADOR,
QUE NOS LLENAS DE GOZO
Y SANTO VALOR.

IV
UNIDOS LOAD,
A LA GRAN TRINIDAD
QUE ES LA FUENTE DE GRACIA
VIRTUD Y VERDAD."""
  },
  {
    "number": 5, "title": "¡ADORADLE!", "category": "Adoración", "originalKey": "Ab", "bpm": 92,
    "lyrics": """I
DAD AL PADRE TODA GLORIA,
DAD AL HIJO TODO HONOR,
Y AL ESPÍRITU DIVINO,
ALABANZAS DE LOOR.

CORO
ADORADLE, ADORADLE,
ADORAD AL SALVADOR;
TRIBUTADLE TODA GLORIA,
PUEBLO SUYO POR SU GRANDE AMOR.

II
¡ADORADLE, OH IGLESIA!
POR JESÚS TU REDENTOR,
RESCATADA POR SU GRACIA,
LIBRE POR SU GRANDE AMOR.

III
ENTONADLE UN CANTO NUEVO,
HUESTES LIBRES DEL SEÑOR;
TIERRA, CIELOS, MAR Y LUNA,
GLORIA DAN AL TRINO DIOS.

ÚLTIMO CORO
YO TE ADORO, YO TE ADORO,
YO TE ADORO, BUEN JESÚS,
YO TE ADORO REVERENTE,
¡OH, CORDERO SANTO DE MI DIOS!"""
  },
  {
    "number": 6, "title": "ROCA DE LA ETERNIDAD", "category": "Clásicos", "originalKey": "Bb", "bpm": 85,
    "lyrics": """I
ROCA DE LA ETERNIDAD,
FUISTE ABIERTA PARA MI
SÉ MI ESCONDEDERO FIEL;
SÓLO ENCUENTRO PAZ EN TI,
RICO, LIMPIO MANANTIAL,
EN EL CUAL LAVADO FUI.

II
AUNQUE FUESE SIEMPRE FIEL,
AUNQUE LLORE SIN CESAR,
DEL PECADO NO PODRÉ
JUSTIFICACIÓN LOGRAR;
SÓLO EN TI TENIENDO FE
DEUDA TAL PODRÉ PAGAR.

III
MIENTRAS TENGA QUE VIVIR,
MI POSTRER SUSPIRO DAR,
CUANDO VAYA A RESPONDER
EN TU AUGUSTO TRIBUNAL,
SÉ MI ESCONDEDERO FIEL,
ROCA DE LA ETERNIDAD."""
  },
  {
    "number": 7, "title": "SUBLIME GRACIA", "category": "Clásicos", "originalKey": "G", "bpm": 75,
    "lyrics": """I
SUBLIME GRACIA DEL SEÑOR
QUE UN INFELIZ SALVÓ;
FUI CIEGO MAS HOY MIRO YO,
PERDIDO Y ÉL ME HALLÓ.

II
SU GRACIA ME ENSEÑÓ A TEMER,
MIS DUDAS AHUYENTÓ,
¡OH CUÁN PRECIOSO FUE A MI SER
AL DAR MI CORAZÓN!

III
EN LOS PELIGROS O AFLICCIÓN
QUE YO HE TENIDO AQUÍ;
SU GRACIA SIEMPRE ME LIBRÓ
Y ME GUIARÁ FELIZ.

IV
Y CUANDO EN SION POR SIGLOS MIL
BRILLANDO ESTÉ CUAL SOL;
YO CANTARÉ POR SIEMPRE ALLÍ
SU AMOR QUE ME SALVÓ."""
  },
  {
    "number": 8, "title": "TE ADORO BUEN SALVADOR", "category": "Adoración", "originalKey": "D", "bpm": 80,
    "lyrics": """I
DIVINO JESÚS, CON TODO FERVOR,
TRIBUTO A TI, MI DULCE CANTAR.
PUES SÓLO TU AMOR ME PUDO SALVAR,
¡TE ADORO BUEN SALVADOR!

CORO
SI CERCA YO VOY DE TI, MI SEÑOR,
SE VA MI PESAR, SE VA MI DOLOR,
¡ES GRATO, OH SÍ, VIVIR PARA TI!
¡TE ADORO BUEN SALVADOR!

II
DIVINO JESÚS, TU SANTO AMOR,
ME DA DICHA Y PAZ, ME DA SANTIDAD,
CUAL TÚ, NADIE HAY TAN RICO EN BONDAD.
¡TE ADORO BUEN SALVADOR!

III
DIVINO JESÚS, POR GRACIA Y FAVOR,
TU LUZ Y AMISTAD ME BRINDAS DOQUIER,
SI DÉBIL ESTOY, ME DAS TU PODER,
¡TE ADORO BUEN SALVADOR!

IV
DIVINO JESÚS, ¡PRECIOSO SEÑOR!
¿CON QUÉ LOGRARÉ PODER COMPENSAR,
TU MÍSTICO AMOR, EXCELSO, SIN PAR?
¡TE ADORO BUEN SALVADOR!"""
  },
  {
    "number": 9, "title": "CANTARES CRISTIANOS", "category": "Alabanza", "originalKey": "C", "bpm": 90,
    "lyrics": """I
CANTARES CRISTIANOS, SUBLIME EXPRESIÓN
DEL ALMA QUE OFRECE SU INCIENSO DE AMOR;
A TI PADRE EXCELSO QUE POR COMPASIÓN,
NOS DISTE EN CRISTO UN GRAN SALVADOR.

CORO
CANTEMOS HERMANOS A LA TRINIDAD,
QUE MIL BENDICIONES NOS DA SIN CESAR.
LA TERSA HERMOSURA DE LA SANTIDAD,
INSPIRE ARDIENTE EL SACRO CANTAR.

II
ESCUCHA BONDOSO, BENDITO JESÚS
EL CANTO DE GLORIA QUE LA MULTITUD,
AL VERSE SALVADA POR TI EN LA CRUZ,
TE OFRECE GOZOSA CON FE Y GRATITUD.

III
¡ESPÍRITU SANTO, BUEN CONSOLADOR!
UNIDOS LOS FIELES CON FE Y DEVOCIÓN,
HUMILDES TE ALABAN CON TODO FERVOR,
CUAL MUESTRA INEFABLE DE SU ADORACIÓN.

IV
AL PADRE, AL HIJO, AL CONSOLADOR,
UNÍSONOS TODOS FERVIENTES ROGAD:
SU GRACIA NOS CUBRA, CON FÉRVIDO AMOR,
Y FIEL NOS IMPARTA SU LUZ Y VERDAD."""
  },
  {
    "number": 10, "title": "¡OH, QUÉ AMIGO!", "category": "Clásicos", "originalKey": "F", "bpm": 80,
    "lyrics": """I
¡OH, QUÉ AMIGO NOS ES CRISTO!
ÉL LLEVÓ NUESTRO DOLOR,
Y NOS MANDA QUE LLEVEMOS
TODO A DIOS EN ORACIÓN.
¿VIVE EL HOMBRE DESPROVISTO
DE PAZ, GOZO Y SANTO AMOR?
ESTO ES PORQUE NO LLEVAMOS
TODO A DIOS EN ORACIÓN.

II
¿VIVES DÉBIL Y CARGADO
DE CUIDADOS Y TEMOR?
A JESÚS, REFUGIO ETERNO
DILE TODO EN ORACIÓN.
¿TE DESPRECIAN TUS AMIGOS?
CUÉNTASELO EN ORACIÓN;
EN SUS BRAZOS DE AMOR TIERNO
PAZ TENDRÁ TU CORAZÓN.

III
JESUCRISTO ES NUESTRO AMIGO,
DE ESTO PRUEBAS ÉL NOS DIO
AL SUFRIR EL CRUEL CASTIGO
QUE EL CULPABLE MERECIÓ.
Y SU PUEBLO REDIMIDO
HALLARÁ SEGURIDAD
FIANDO EN ESTE AMIGO ETERNO
Y ESPERANDO EN SU BONDAD."""
  },
  {
    "number": 11, "title": "EN JESUCRISTO, MÁRTIR DE PAZ", "category": "Consolación", "originalKey": "G", "bpm": 85,
    "lyrics": """I
EN JESUCRISTO, MÁRTIR DE PAZ,
EN HORAS NEGRAS DE TEMPESTAD,
HALLAN LAS ALMAS DULCE SOLAZ,
GRATO CONSUELO, FELICIDAD.

CORO
GLORIA CANTEMOS AL REDENTOR,
QUE POR NOSOTROS QUISO MORIR;
LA SANTA GRACIA DEL SALVADOR,
SIEMPRE DIRIJA NUESTRO VIVIR.

II
EN LOS PELIGROS, EN EL DOLOR,
A CADA PASO SU PROTECCIÓN,
CALMA LA INFUNDE, SANTO VIGOR,
NUEVOS ALIENTOS AL CORAZÓN.

III
CUANDO EN LA LUCHA FALTA LA FE,
Y EL ALMA SIENTA DESFALLECER,
CRISTO NOS DICE: «YO OS COLMARÉ
DE RICA GRACIA, SANTO PODER»"""
  },
  {
    "number": 12, "title": "TENGO UN PASTOR", "category": "Confianza en Dios", "originalKey": "D", "bpm": 80,
    "lyrics": """I
TENGO UN PASTOR QUE DEL ALMA AHUYENTA EL DUELO,
TENGO UN PASTOR CUYO NOMBRE ES SIN IGUAL;
TENGO UN PASTOR QUE ME IMPARTE SU CONSUELO,
AL VERME SOLO EN MIS LUCHAS CONTRA EL MAL.

CORO
TENGO UN PASTOR, AMANTE PASTOR,
MI TIERNO PASTOR ES CRISTO.

II
TENGO UN PASTOR QUE LAS TEMPESTADES CALMA,
TENGO UN PASTOR QUE APACIGUA EL TURBIO MAR;
TENGO UN PASTOR QUE ME SANA CUERPO Y ALMA,
Y TIERNAMENTE MITIGA MI PESAR.

III
TENGO UN PASTOR QUE DERROTA AL ENEMIGO,
TENGO UN PASTOR QUE VICTORIA Y TRIUNFO DA;
TENGO UN PASTOR QUE DOQUIERA VA CONMIGO,
Y EN LA LUCHA CRUEL A MI LADO SIEMPRE ESTÁ.

IV
TENGO UN PASTOR CUYO NOMBRE ES ADMIRABLE,
TENGO UN PASTOR, RICO DON DEL DIOS DE AMOR;
MI BUEN PASTOR SOBRE TODO ES ADORABLE,
SUPREMO BIEN ES JESÚS MI SALVADOR."""
  },
  {
    "number": 13, "title": "¡OH CRISTO MÍO!", "category": "Adoración", "originalKey": "G", "bpm": 75,
    "lyrics": """I
¡OH!, CRISTO MÍO, ERES TÚ MI AMIGO FIEL;
SEGURO AMPARO SÓLO EN TI TENDRÉ,
EN MIS AFLICCIONES, BUEN JESÚS, IRÉ A TI,
Y CONSUELO Y DICHA ME DARÁS ¡OH! SI.

CORO
CRISTO, VEN MÁS CERCA;
PAZ PERFECTA EN MI ALMA PON;
CERCA, SÍ MAS CERCA,
DE MI CORAZÓN.

II
CUANDO EN LA NOCHE, VEA YO ESTRELLAS MIL,
TU VOZ HERMOSA PUEDA MI ALMA OÍR.
HAZ QUE YO MEDITE EN TU TIERNO Y DULCE AMOR,
Y QUE YO TE ALABE, LLENO DE FERVOR.

III
CUANDO ESTA VIDA TENGA YO QUE ABANDONAR,
CORONA HERMOSA TÚ ME CEÑIRÁS;
Y CON DULCE CANTO TU BONDAD ALABARÉ,
Y EN MANSIÓN DE GLORIA SIEMPRE MORARÉ."""
  },
  {
    "number": 14, "title": "¡SEÑOR, YO TE CONOZCO!", "category": "Adoración", "originalKey": "Em", "bpm": 70,
    "lyrics": """I
¡SEÑOR YO TE CONOZCO! LA NOCHE AZUL SERENA
ME DICE DESDE LEJOS: «TU DIOS SE ESCONDE ALLÍ;»
PERO LA NOCHE OBSCURA, LA DE NUBLADOS LLENAS,
ME DICE MÁS PUJANTE: «TU DIOS SE ACERCA A TI»

II
TE ACERCAS, SI; CONOZCO LAS ORLAS DE TU MANTO
EN ESA ARDIENTE NUBE CON QUE CEÑIDO ESTÁS;
EL RESPLANDOR CONOZCO DE TU SEMBLANTE SANTO,
CUANDO AL CRUZAR EL ÉTER RELAMPAGUEANDO VAS.

III
¿QUIÉN ANTE TI PARECE? ¿QUIÉN ES EN TU PRESENCIA
MÁS QUE UN ARTISTA SECA QUE EL AIRE VA A ROMPER?
TUS OJOS SON EL DÍA, TU SOPLO LA EXISTENCIA;
LOS CÁNTICOS QUE LLEGAN AL GRANDE JEHOVÁ.

IV
¡SEÑOR, YO TE CONOZCO! MI CORAZÓN TE ADORA;
MI ESPÍRITU DE HINOJOS ANTE TUS PIES ESTÁ;
PERO MI LENGUA CALLA, PORQUE MI LENGUA IGNORA
LOS CÁNTICOS QUE LLEGAN AL GRANDE JEHOVÁ."""
  },
  {
    "number": 15, "title": "ES PARA TODOS YA", "category": "Espíritu Santo", "originalKey": "A", "bpm": 90,
    "lyrics": """I
¡OH HERMANO! ¿HAS SENTIDO EL PODER PENTECOSTAL
INGRESAR A TU ALMA Y QUEMAR EL ÁNIMO CARNAL?
CON SU FUEGO EL ESPÍRITU TE SANTIFICARÁ,
SI AHORA LE RECIBES, Y ES PARA TODOS YA.

CORO
SÍ, ES PARA TODOS YA;
QUIEN BUSCARE HALLARÁ;
CRISTO EN LA CRUZ MURIÓ
Y ESTA BENDICIÓN COMPRÓ
¡OH SÍ! PARA DARLA A TODOS YA.

II
DIOS OFRECE ESTE DON DE SANTIDAD DE CORAZÓN,
A SUS HIJOS OBEDIENTES, LOS QUE TIENEN SU PERDÓN;
PURIFICA LOS DESEOS, QUITA LA RAÍZ DEL MAL
Y CONSUME CADA ANSIA Y TENDENCIA MUNDANAL.

III
EL DIVINO FUEGO QUITARA TUS DUDAS Y TEMOR
Y NO HABRÁ MÁS TINIEBLAS, MAS HABRÁ PERFECTO AMOR:
A VIVIR TE AYUDARA EN ESTE MUNDO SIN PECAR,
Y CON LIBERTAD GOZOSA TÚ PODRÁS TESTIFICAR.

IV
LA PRESENCIA MILAGROSA DE ESTE GRAN CONSOLADOR
NOS DA FUERZAS Y VIRTUD EN EL SERVICIO DEL SEÑOR;
NOS DA PAZ INEXPLICABLE, SANTO GOZO CELESTIAL,
NOS DA HIMNOS DE VICTORIA Y LA VIDA ETERNAL."""
  },
  {
    "number": 16, "title": "¿TE SIENTES CASI?", "category": "Evangelismo e Invitación", "originalKey": "G", "bpm": 80,
    "lyrics": """I
¿TE SIENTES CASI RESUELTO YA?
¿TE FALTA POCO PARA CREER?
PUES, ¿POR QUÉ DICES A JESUCRISTO
«HOY NO, MAÑANA TE SEGUIRÉ»

II
¿TE SIENTES CASI RESUELTO YA?
PUES VENCE EL CASI Y A CRISTO VEN,
QUE HOY ES TIEMPO, PERO MAÑANA
SOBRADO TARDE PUDIERA SER.

III
SABE QUE EL CASI NO ES DE VALOR
EN LA PRESENCIA DEL JUSTO JUEZ.
¡AY DEL QUE MUERE CASI CREYENDO!
¡COMPLETAMENTE PERDIDO ES!"""
  },
  {
    "number": 17, "title": "SANTIDAD A JEHOVÁ", "category": "Consagración", "originalKey": "Eb", "bpm": 85,
    "lyrics": """I
LLAMADO A SANTIDAD, PUEBLO DE DIOS,
QUE CON SU SANGRE JESÚS OS COMPRÓ,
QUE DE ENTRE EL MUNDO DE MAL OS SACÓ,
DE ESCLAVITUD DE PECADO OS LIBRÓ.

CORO
SANTIDAD HOY A JEHOVÁ, NUESTRO CANTO Y LOOR,
SANTIDAD HOY A JEHOVÁ, MIENTRAS VAMOS A SION,
SÍ, CANTAD, CANTAD CANCIÓN,
SANTIDAD HOY A JEHOVÁ SEA POR SIEMPRE.

II
CREADOS A SANTIDAD, HIJOS DE LUZ,
CON JESUCRISTO DEBÉIS SIEMPRE ANDAR,
CON ALBO MANTO, SIN MANCHA O PECAR,
LLENA VUESTRA ALMA DE ESPÍRITU Y LUZ.

III
LLAMADA A SANTIDAD, ESPOSA FIEL,
ESPERA SIEMPRE AL ESPOSO Y SEÑOR,
AL CIELO ELEVA TU ROSTRO Y AMOR
HASTA QUE EN GLORIA APAREZCA EMMANUEL."""
  },
  {
    "number": 18, "title": "EL GRAN MÉDICO", "category": "Evangelismo e Invitación", "originalKey": "E", "bpm": 85,
    "lyrics": """I
LA TIERNA VOZ DEL SALVADOR,
NOS HABLA CONMOVIDA:
VENID AL MÉDICO DE AMOR,
QUE DA A LOS MUERTOS VIDA.

CORO
ÉL TIENE TODA POTESTAD,
PUEDE SANAR LA ENFERMEDAD;
LLENO DE GRACIA Y DE BONDAD,
ES NUESTRO JESUCRISTO.

II
CONFÍA, TÚ, QUIEN SATANÁS,
POR AÑOS HA LIGADO,
TU FE TE SANA, VETE EN PAZ,
MEDIANTE SU PALABRA.

III
LOS SORDOS OYEN, CIEGOS VEN,
PUES CRISTO ES EL QUE HABLA,
LOS COJOS SANAN Y ANDAN BIEN,
MEDIANTE SU PALABRA.

IV
ASÍ SEÑALES SEGUIRÁN,
A LOS QUE SON CREYENTES,
DEMONIOS FUERA ECHARÁN,
Y SANARÁN LAS GENTES."""
  },
  {
    "number": 19, "title": "DE MI TIERNO SALVADOR", "category": "Testimonio", "originalKey": "G", "bpm": 90,
    "lyrics": """I
DE MI TIERNO SALVADOR
CANTARÉ EL INMENSO AMOR,
GLORÍAME EN EL FAVOR DE JESÚS;
DE TINIEBLAS ME LLAMÓ,
DE CADENAS ME LIBRÓ,
DE LA MUERTE ME SALVÓ, MI JESÚS.

CORO
¡MI JESÚS! ¡MI JESÚS!
¡CUÁN PRECIOSO ES EL NOMBRE DE JESÚS!
CON SU SANGRE ME LIMPIÓ,
DE SU GOZO ME LLENÓ,
DE SU VIDA ME DOTÓ, MI JESÚS.

II
¡OH, QUÉ TRISTE CONDICIÓN
DEL IMPÍO CORAZÓN!
ME SALVÓ DE PERDICIÓN, MI JESÚS.
DEL PECADO, EL PERDÓN,
DE LA RUINA, SALVACIÓN;
POR TRISTEZA, BENDICIÓN DIO JESÚS.

III
EN EL MUNDO AL VAGAR,
SOLITARIO SIN HOGAR,
NO SABÍA QUE DULCE PAZ DA JESÚS.
MAS LAS LÁGRIMAS DE AYER,
HAN PASADO, Y PLACER
YA COMIENZO A TENER EN JESÚS.

IV
DE LOS FALSO A SU VERDAD,
DE LO INMUNDO A SANTIDAD,
YA ME TRAJO LA BONDAD DE JESÚS.
HECHOS FUERTES EN VIRTUD,
DE SU PERENNAL SALUD,
HIMNOS DAD DE GRATITUD A JESÚS."""
  },
  {
    "number": 20, "title": "PARA SIEMPRE SANTIDAD", "category": "Consagración", "originalKey": "D", "bpm": 85,
    "lyrics": """I
MUCHO MÁS ES QUE UN IDEAL,
LA PRECIOSA SANTIDAD,
PALPITANTE BENDICIÓN ACTUAL,
AXIOMÁTICA VERDAD.

CORO
¿QUIÉN A DIOS SU SER LE DA?
¿QUIÉN HOY SE CONSAGRARÁ?
CON GRAN EFICACIA, OBRA LA GRACIA,
PARA SIEMPRE SANTIDAD.

II
CRISTO QUIERE QUE SEAMOS LUZ,
AL MUNDO DE OSCURIDAD,
DISIPEMOS AL NEGRO CAPUZ,
VIVIENDO LA SANTIDAD.

III
LA EXPERIENCIA DE LA SANTIDAD,
ES TEMPLANZA, PAZ, AMOR,
FE, PACIENCIA, GRATITUD, BONDAD,
TOLERANCIA Y VALOR.

IV
ES EL SANTO ESPÍRITU, VIRTUD,
Y LA SANTIDAD CABAL,
EMANCIPA DE LA ESCLAVITUD,
DEL PECADO ORIGINAL."""
  },
  {
    "number": 21, "title": "CUANDO ALLÁ SE PASE LISTA", "category": "La Venida del Señor", "originalKey": "Ab", "bpm": 110,
    "lyrics": """I
CUANDO LA TROMPETA SUENE
EN AQUEL DÍA FINAL
E QUE EL ALBA ETERNA ROMPA EN CLARIDAD,
CUANDO LAS NACIONES SALVAS
A SU PATRIA LLEGUEN YA,
Y QUE SEA PASADA LISTA, ALLÍ HE DE ESTAR.

CORO
CUANDO ALLÁ SE PASE LISTA,
CUANDO ALLÁ SE PASE LISTA,
CUANDO ALLÁ SE PASE LISTA,
A MI NOMBRE YO FELIZ RESPONDERÉ.

II
EN AQUEL DÍA SIN NIEBLAS
EN QUE MUERTE YA NO HABRÁ
Y SU GLORIA EL SALVADOR IMPARTIRÁ;
CUANDO LOS LLAMADOS ENTREN
A SU CELESTIAL HOGAR,
Y QUE SEA PASADA LISTA, ALLÍ HE DE ESTAR.

III
TRABAJEMOS POR EL MAESTRO
DESDE EL ALBA AL VISLUMBRAR;
SIEMPRE HABLEMOS DE SU AMOR Y FIEL BONDAD,
CUANDO TODO AQUÍ FENEZCA
Y NUESTRA OBRA CESE YA,
Y QUE SEA PASADA LISTA, ALLÍ HE DE ESTAR."""
  },
  {
    "number": 22, "title": "YO ME RINDO A ÉL", "category": "Consagración", "originalKey": "D", "bpm": 80,
    "lyrics": """I
TODO A CRISTO YO ME RINDO,
CON EL FIN DE SERLE FIEL;
PARA SIEMPRE QUIERO AMARLE
Y AGRADARLE SÓLO A ÉL.

CORO
YO ME RINDO A ÉL,
YO ME RINDO A ÉL.
TODO A CRISTO YO ME ENTREGO,
QUIERO SERLE FIEL.

II
TODO A CRISTO YO ME RINDO,
A SUS PIES POSTRADO ESTOY;
LOS PLACERES HE DEJADO
Y LE SIGO DESDE HOY.

III
TODO A CRISTO YO ME RINDO,
SÍ, DE TODO CORAZÓN,
YO LE ENTREGO ALMA Y CUERPO
BUSCO HOY SU SANTA UNCIÓN.

IV
TODO A CRISTO HE RENDIDO,
SIENTO EL FUEGO DE SU AMOR;
¡OH, QUE GOZO HAY EN MI ALMA!
¡GLORIA, GLORIA A MI SEÑOR!"""
  },
  {
    "number": 23, "title": "¡CRISTO VIVE!", "category": "Alabanza", "originalKey": "Ab", "bpm": 100,
    "lyrics": """I
RESUCITÓ TRIUNFANTE, JESÚS MI SALVADOR,
YA VIVE EL REY GLORIOSO, DEL MUNDO REDENTOR;
SU DULCE VOZ ESCUCHO, CONMIGO SIEMPRE VA;
PALPAR SU MANO NO PUEDO; MUY CERCA ESTÁ.

CORO
¡ÉL VIVE YA! ¡TRIUNFANTE VIVE YA!
EL VICTORIOSO SALVADOR CONMIGO SIEMPRE VA.
¡ÉL VIVE YA! ¡SÍ, CRISTO VIVE AQUÍ!
¡YO SÉ QUE CRISTO VIVE EN MI, YO SÉ QUE VIVE EN MI!

II
EN TODO EL MUNDO BROTA SU AMOR Y SU PODER,
SU GRAN MISERICORDIA ME SIGUE POR DOQUIER:
CUAL BUEN PASTOR ME GUÍA, FELIZ YO VIVO AQUÍ,
PUES SIENTO SU PRESENCIA, ÉL VIVE EN MI.

III
¡CANTAD, CANTAD, CRISTIANOS! CON ALMA Y VOZ CANTAD,
A CRISTO, REY DE GLORIA, CON JÚBILO ACLAMAD;
ÉL NOS HA PROMETIDO QUE AL MUNDO VOLVERÁ,
EL DÍA YA SE ACERCA, JESÚS VENDRÁ."""
  },
  {
    "number": 24, "title": "ME GUÍA ÉL, CON CUÁNTO AMOR", "category": "Confianza en Dios", "originalKey": "D", "bpm": 85,
    "lyrics": """I
ME GUÍA ÉL, CON CUÁNTO AMOR,
ME GUÍA SIEMPRE MI SEÑOR;
AL VER MI ESFUERZO EN SERLE FIEL,
CON CUÁNTO AMOR ME GUÍA ÉL.

CORO
ME GUÍA ÉL, ME GUÍA ÉL
CON CUÁNTO AMOR ME GUÍA ÉL,
NO ABRIGO DUDAS NI TEMOR,
PUES ME CONDUCE EL BUEN PASTOR.

II
EN EL ABISMO DEL DOLOR
O EN DONDE BRILLE EL SOL MEJOR,
EN DULCE PAZ O EN LUCHA CRUEL,
CON GRAN BONDAD ME GUÍA ÉL.

III
TU MANO QUIERO YO TOMAR
JESÚS, Y NUNCA VACILAR,
PUES SÓLO A QUIEN TE SIGUE FIEL
SE OYÓ DECIR: ME GUÍA ÉL.

IV
Y MI CARRERA AL TERMINAR
Y ASÍ MI TRIUNFO REALIZAR
NO HABRÁ NI DUDAS NI TEMOR
PUES ME GUIARÁ EL BUEN PASTOR."""
  },
  {
    "number": 25, "title": "UN SACRIFICIO VIVO", "category": "Consagración", "originalKey": "F", "bpm": 80,
    "lyrics": """I
¿HAS BUSCADO LA PAZ Y DIVINO SOLAZ
Y DESEAS QUE CREZCA TU FE?.
PERO TE ES MENESTER ALMA Y CUERPO TRAER
AL ALTAR CUAL OFENDA A TU REY.

CORO
¿TE HAS PUESTO EN EL SANTO ALTAR DE TU DIOS?
¿TE HAS ENTREGADO AL SEÑOR?
SÓLO ASÍ TÚ TENDRÁS SU DESCANSO Y SOLAZ,
Y SUS RICAS DELICIAS DE AMOR.

II
PARA ANDAR CON JESÚS Y GOZARTE EN LA LUZ,
Y VIVIR LIBRE DE LA MALDAD;
LLEVA PRESTO AL ALTAR PARA SACRIFICAR
LO QUE TENGAS A SU VOLUNTAD.

III
NO PODEMOS SABER, NI POR GRACIA TENER;
LA DULZURA DE SU BENDICIÓN;
DE COLMARNOS DE AMOR DEL BENDITO SEÑOR,
SIN RENDIRNOS EN CONSAGRACIÓN.

IV
SATISFECHO ESTARÁS, PAZ Y GOZO TENDRÁS,
UN AMOR CUAL LAS ONDAS DEL MAR;
Y VERÁS LO QUE ES EL SENTARTE A TUS PIES,
CUANDO TRAIGAS TU TODO AL ALTAR."""
  },
  {
    "number": 26, "title": "TEMPLOS DE DIOS SOIS", "category": "Espíritu Santo", "originalKey": "G", "bpm": 85,
    "lyrics": """I
TEMPLOS DE DIOS SOIS, ASÍ ESTÁ ESCRITO,
TEMPLOS DE SU ESPÍRITU DE VERDAD;
¿A ÉL LE ES DADA, LIBRE ENTRADA?
¿FRANCA ES LA PUERTA DE TU VOLUNTAD?

CORO
DEJAR ENTRAR, PARA, MORAR,
AL SANTO ESPÍRITU;
ÉL HA VENIDO, PACTO CUMPLIDO,
BENDITO ESPÍRITU DE DIOS.

II
EL QUE PERDONA, QUIERE LIMPIARTE;
TODA LA ESCORIA DE TU ALMA QUITAR;
PURIFICADO, MUERTO AL PECADO,
EL SANTO ESPÍRITU PODRÁ ENTRAR.

III
¡OH! PEREGRINO EN EL DESIERTO,
ENTRA EN LA TIERRA DE LECHE Y MIEL;
SANTIFICADO, DE DIOS LLENADO,
GUIADO SERÁS POR SU ESPÍRITU FIEL."""
  },
  {
    "number": 27, "title": "PENTECOSTÉS PARA TODOS", "category": "Espíritu Santo", "originalKey": "G", "bpm": 90,
    "lyrics": """I
DIOS NO NOS DEJA HUÉRFANOS
MAS COMO PROMETIÓ,
NOS MANDA EL SANTO ESPÍRITU,
QUE LLENA DE SU GRAN VIRTUD
AL SER QUE LE ESPERÓ.

CORO
¿HA VENIDO A TI?
¿HA VENIDO A TI
EL ESPÍRITU CONSOLADOR?
DIOS CONVENCERÁ AL MUNDO DE MAL
CUANDO VENGA EL CONSOLADOR.

II
¡OH! SANTOS, DIOS OS LLAMA HOY,
SU PLENITUD TOMAD;
ES PARA TODOS POR IGUAL
EL SANTO HUÉSPED CELESTIAL,
ESPÍRITU DE VERDAD.

III
JESÚS PROMETE UN PENTECOSTÉS
A CADA CORAZÓN;
POSTRADOS, PUES, ROGUÉMOSLE,
Y ESPEREMOS POR LA FE,
EL PROMETIDO DON.

IV
CREYENTES, PARA TODOS HAY
EL GRAN CONSOLADOR,
Y LAS SEÑALES SEGUIRÁN,
EN OTRAS LENGUAS HABLARÁN
PROMESAS DE VERDAD."""
  },
  {
    "number": 28, "title": "LLAMA PENTECOSTAL", "category": "Espíritu Santo", "originalKey": "Em", "bpm": 110,
    "lyrics": """I
FUEGO DIVINO, CLAMAMOS A TI,
VEN DE LO ALTO, DESCIENDE AQUÍ;
¡OH, VEN, DESPIÉRTANOS CON TU FULGOR!
¡VEN, Y AVÍVANOS CON TU CALOR!

CORO
BAJA DEL CIELO, BENDITO FUEGO,
BAJA PODER CELESTIAL;
BAJA DEL CIELO, BENDITO FUEGO,
VEN, LLAMA PENTECOSTAL.

II
BAJA, ESPÍRITU CONSOLADOR,
BAJA, Y LLÉNANOS DE SANTO AMOR;
AL MUNDO BAJA CUAL DIJO JESÚS,
DANOS PODER, VIDA, GRACIA Y LUZ.

III
EN MI ALMA ARDE, ¡OH! LLAMA DE AMOR,
ARDE EN MI PECHO Y DAME VALOR;
CONSUME TODOS LOS RESTOS DEL MAL,
DESCIENDE YA, FUEGO PENTECOSTAL."""
  },
  {
    "number": 29, "title": "MORANDO EN JESÚS", "category": "Consagración", "originalKey": "G", "bpm": 85,
    "lyrics": """I
APRENDÍ EL GRAN SECRETO
DE MORAR EN EL SEÑOR;
MI DESCANSO ES COMPLETO
SIN AFÁN Y SIN DOLOR;
TOMO MI VIGOR EN CRISTO,
ÉL MI FORTALEZA ES,
Y SU GRAN PODER HE VISTO,
VIVO EN SU VALIDEZ.

CORO
MORO EN CRISTO MI JESÚS
Y ME GOZO EN SU LUZ;
PUES MI VIDA ESTÁ ESCONDIDA
EN EL SENO DE SU AMOR.

II
ESTE MUNDO HE DEJADO
EL VIEJO HOMBRE ME APARTÉ;
PUES ESTOY CRUCIFICADO
CRISTO VIVE EN MI POR FE;
ÉL ME DA SU MISMA MENTE,
HEREDERO SOY CON ÉL,
DE MI GOZO ÉL ES LA FUENTE,
SU PALABRA ES COMO MIEL.

III
SU PRESENCIA ES PRECIOSA
Y MIS CULPAS YA QUITÓ;
EN LA SANTIDAD GLORIOSA
POR SU SANGRE VIVO YO.
SU ESPÍRITU ME HA DADO
QUIEN ME ENSEÑA DEL SEÑOR,
Y MI VIDA HA LLENADO,
CON SU PAZ Y PURO AMOR."""
  },
  {
    "number": 30, "title": "¡TE QUIERO, MI SEÑOR!", "category": "Consagración", "originalKey": "C", "bpm": 75,
    "lyrics": """I
¡TE QUIERO, MI SEÑOR!
HABITA EN MÍ,
Y VENCEDOR SERÉ,
POR FE EN TI.

CORO
TE QUIERO, SÍ, TE QUIERO,
SIEMPRE TE ANHELO;
BENDÍCEME AHORA,
ACUDO A TI

II
¡TE QUIERO, OH, JESÚS,
MI SALVADOR!
OH, HAZME EN VERDAD
TU SERVIDOR.

III
TU VOLUNTAD, SEÑOR,
ENSÉÑAME;
Y DE TU GRAN AMOR,
¡OH! CÓLMAME.

IV
OH, MI GRAN BIENHECHOR,
EN TENTACIÓN;
CONCÉDEME VALOR
Y PROTECCIÓN."""
  }
]
