# -*- coding: utf-8 -*-
import re
import json

# We will store the entire raw OCR text from the PDF pages in a string
ocr_text = """
1. LOORES DAD A CRISTO EL REY 
I 
LOORES DAD A CRISTO EL REY, 
SUPREMA POTESTAD; 
//DE SU DIVINO AMOR LA LEY, 
POSTRADOS ACEPTAD// 
 
II 
VOSOTROS, HIJOS DE ISRAEL, 
RESIDUO DE LA GREY; 
//LOORES DAD A EMMANUEL, 
Y PROCLAMADLE REY// 
 
III 
GENTILES QUE POR GRACIA DE ÉL 
GOZÁIS DE LIBERTAD, 
//AL QUE DE VUESTRO AJENJO Y HIEL 
OS LIBRA, HOY LOAD// 
 
IV 
NACIONES TODAS, ESCUCHAD 
Y OBEDECED SU LEY 
//DE GRACIA Y DE SANTIDAD, 
Y PROCLAMADLE REY// 
 
V 
DIOS QUIERA QUE CON LOS QUE ESTÁN 
DEL TRONO EN DERREDOR, 
//CANTEMOS POR LA ETERNIDAD 
A CRISTO EL SALVADOR// 

2. NUESTRO IDEAL 
I 
COMPAÑEROS NAZARENOS QUE LUCHAMOS POR JESÚS, 
EN LA AMÉRICA LATINA GANANDO ALMAS PARA DIOS, 
REDOBLEMOS NUESTRO ESFUERZO HACIENDO BRILLAR LA LUZ 
DE PLENA SALVACIÓN. 
 
CORO 
GANARÉ A MIS COMPATRIOTAS, 
GANARÉ A MIS COMPATRIOTAS, 
GANARÉ A MIS COMPATRIOTAS, 
EN NOMBRE DE JESÚS. 
 
II 
UN MILLÓN DE ALMAS SALVADAS ES AHORA NUESTRO IDEAL 
QUE LAVADAS SEAN POR CRISTO NUESTRO GRANDE SALVADOR; 
A LAS CUALES CON TERNURA GUIEMOS A LA SANTIDAD, 
POR EL CONSOLADOR. 
 
III 
CADA MIEMBRO DE LA IGLESIA LUCHAR DEBE POR GANAR 
A LOS POBRES PECADORES MUERTOS EN SU GRAN PECAR, 
HASTA HACER QUE EL EVANGELIO LO CONOZCA MÁS Y MÁS 
EL MUNDO CONTUMAZ.  
 
IV 
NAZARENOS, NAZARENAS, DIOS NOS LLAMA A COOPERAR 
EN SALVAR AL MUNDO MALO POR SU GRATIS SALVACIÓN, 
TRABAJEMOS CON ANHELO HASTA EL ÉXITO ALCANZAR, 
POR CRISTO EL SALVADOR. 

3. ALZA TU CANTO, ¡OH LENGUA MÍA! 
I 
AL CIELO VUELEN LOS ECOS SANTOS 
QUE ARRANCO ALEGRE DE MI LAÚD; 
AL CIELO VUELEN MIS DULCES CANTOS, 
MIS DULCES CANTOS DE GRATITUD. 
 
CORO 
¡ALZA TU CANTO, OH LENGUA MÍA! 
¡ALZA TU CANTO MI CORAZÓN! 
LLÉNESE EL ALMA DE ALEGRÍA, 
CON ALEGRÍA DE DEVOCIÓN. 
 
II 
YA SIENTO EL FUEGO DE LOS AMORES, 
DE LOS AMORES DEL GRATO EDÉN; 
YA NO ME ACOSAN AQUÍ DOLORES, 
PORQUE CONTEMPLO A JERUSALÉN. 
 
III 
PADRE, EN TU REGIA, SANTA MORADA, 
DONDE LA DICHA NO TIENE FIN; 
ALLÍ MI PATRIA MIRO ESMALTADA 
DE BELLAS FLORES DE TU JARDÍN. 
 
IV 
OH PADRE, IMPÁRTEME TU CONSUELO; 
NADA EN LA TIERRA YO ESPERO YA; 
Y HAZ QUE PUEDA ENTRAR AL CIELO, 
QUE ALLÍ TAN SÓLO MI DICHA ESTÁ. 

4. TE LOAMOS, ¡OH DIOS! 
I 
TE LOAMOS¡OH, DIOS! 
CON UNÁNIME VOZ, 
QUE EN CRISTO TU HIJO 
NOS DISTE PERDÓN. 
 
CORO 
¡ALELUYA! TE ALABAMOS, 
¡CUÁN GRANDE ES TU AMOR! 
¡ALELUYA! TE ADORAMOS, 
BENDITO SEÑOR. 
 
II 
TE LOAMOS, JESÚS, 
QUIEN TU TRONO DE LUZ 
HAS DEJADO POR DARNOS, 
SALUD EN LA CRUZ. 
 
III 
TE DAMOS LOOR, 
SANTO CONSOLADOR, 
QUE NOS LLENAS DE GOZO 
Y SANTO VALOR. 
 
IV 
UNIDOS LOAD, 
A LA GRAN ----- 
QUE ES LA FUENTE DE GRACIA 
VIRTUD Y VERDAD. 

5. ¡ADORADLE! 
I 
DAD AL PADRE TODA GLORIA, 
DAD AL HIJO TODO HONOR, 
Y AL ESPÍRITU DIVINO, 
ALABANZAS DE LOOR. 
 
CORO 
ADORADLE, ADORADLE, 
ADORAD AL SALVADOR; 
TRIBUTADLE TODA GLORIA, 
PUEBLO SUYO POR SU GRANDE AMOR. 
 
II 
¡ADORADLE, OH IGLESIA! 
POR JESÚS TU REDENTOR, 
RESCATADA POR SU GRACIA, 
LIBRE POR SU GRANDE AMOR 
 
III 
ENTONADLE UN CANTO NUEVO, 
HUESTES LIBRES DEL SEÑOR; 
TIERRA, CIELOS, MAR Y LUNA, 
GLORIA DAN AL TRINO DIOS. 
 
ÚLTIMO CORO 
YO TE ADORO, YO TE ADORO, 
YO TE ADORO, BUEN JESÚS, 
YO TE ADORO REVERENTE, 
¡OH, CORDERO SANTO DE MI DIOS! 

6. ROCA DE LA ETERNIDAD 
I 
ROCA DE LA ETERNIDAD, 
FUISTE ABIERTA PARA MI 
SÉ MI ESCONDEDERO FIEL; 
SÓLO ENCUENTRO PAZ EN TI, 
RICO, LIMPIO MANANTIAL, 
EN EL CUAL LAVADO FUI. 
 
II 
AUNQUE FUESE SIEMPRE FIEL, 
AUNQUE LLORE SIN CESAR, 
DEL PECADO NO PODRÉ 
JUSTIFICACIÓN LOGRAR; 
SÓLO EN TI TENIENDO FE 
DEUDA TAL PODRÉ PAGAR. 
 
III 
MIENTRAS TENGA QUE VIVIR, 
MI POSTRER SUSPIRO DAR, 
CUANDO VAYA A RESPONDER 
EN TU AUGUSTO TRIBUNAL, 
SÉ MI ESCONDEDERO FIEL, 
ROCA DE LA ETERNIDAD. 

7. SUBLIME GRACIA 
I 
SUBLIME GRACIA DEL SEÑOR 
QUE UN INFELIZ SALVÓ; 
FUI CIEGO MAS HOY MIRO YO, 
PERDIDO Y ÉL ME HALLÓ. 
 
II 
SU GRACIA ME ENSEÑÓ A TEMER, 
MIS DUDAS AHUYENTÓ, 
¡OH CUÁN PRECIOSO FUE A MI SER 
AL DAR MI CORAZÓN! 
 
III 
EN LOS PELIGROS O AFLICCIÓN 
QUE YO HE TENIDO AQUÍ; 
SU GRACIA SIEMPRE ME LIBRÓ 
Y ME GUIARÁ FELIZ. 
 
IV 
Y CUANDO EN SION POR SIGLOS MIL 
BRILLANDO ESTÉ CUAL SOL; 
YO CANTARÉ POR SIEMPRE ALLÍ 
SU AMOR QUE ME SALVÓ. 

8. TE ADORO BUEN SALVADOR 
I 
DIVINO JESÚS, CON TODO FERVOR, 
TRIBUTO A TI, MI DULCE CANTAR. 
PUES SÓLO TU AMOR ME PUDO SALVAR, 
¡TE ADORO BUEN SALVADOR! 
 
CORO 
SI CERCA YO VOY DE TI, MI SEÑOR, 
SE VA MI PESAR, SE VA MI DOLOR, 
¡ES GRATO, OH SÍ, VIVIR PARA TI! 
¡TE ADORO BUEN SALVADOR! 
 
II 
DIVINO JESÚS, TU SANTO AMOR, 
ME DA DICHA Y PAZ, ME DA SANTIDAD, 
CUAL TÚ, NADIE HAY TAN RICO EN BONDAD. 
¡TE ADORO BUEN SALVADOR! 
 
III 
DIVINO JESÚS, POR GRACIA Y FAVOR, 
TU LUZ Y AMISTAD ME BRINDAS DOQUIER, 
SI DÉBIL ESTOY, ME DAS TU PODER, 
¡TE ADORO BUEN SALVADOR! 
 
IV 
DIVINO JESÚS, ¡PRECIOSO SEÑOR! 
¿CON QUÉ LOGRARÉ PODER COMPENSAR, 
TU MÍSTICO AMOR, EXCELSO, SIN PAR? 
¡TE ADORO BUEN SALVADOR! 

9. CANTARES CRISTIANOS 
I 
CANTARES CRISTIANOS, SUBLIME EXPRESIÓN 
DEL ALMA QUE OFRECE SU INCIENSO DE AMOR; 
A TI PADRE EXCELSO QUE POR COMPASIÓN, 
NOS DISTE EN CRISTO UN GRAN SALVADOR. 
 
CORO 
CANTEMOS HERMANOS A LA ---------, 
QUE MIL BENDICIONES NOS DA SIN CESAR. 
LA TERSA HERMOSURA DE LA SANTIDAD, 
INSPIRE ARDIENTE EL SACRO CANTAR. 
 
II 
ESCUCHA BONDOSO, BENDITO JESÚS 
EL CANTO DE GLORIA QUE LA MULTITUD, 
AL VERSE SALVADA POR TI EN LA CRUZ, 
TE OFRECE GOZOSA CAN FE Y GRATITUD. 
 
III 
¡ESPÍRITU SANTO, BUEN CONSOLADOR! 
UNIDOS LOS FIELES CON FE Y DEVOCIÓN, 
HUMILDES TE ALABAN CON TODO FERVOR, 
CUAL MUESTRA INEFABLE DE SU ADORACIÓN. 
 
IV 
AL PADRE, AL HIJO, AL CONSOLADOR, 
UNÍSONOS TODOS FERVIENTES ROGAD: 
SU GRACIA NOS CUBRA, CON FÉRVIDO AMOR, 
Y FIEL NOS IMPARTA SU LUZ Y VERDAD. 

10. ¡OH, QUÉ AMIGO! 
I 
¡OH, QUÉ AMIGO NOS ES CRISTO! 
ÉL LLEVÓ NUESTRO DOLOR, 
Y NOS MANDA QUE LLEVEMOS 
TODO A DIOS EN ORACIÓN. 
¿VIVE EL HOMBRE DESPROVISTO 
DE PAZ, GOZO Y SANTO AMOR? 
ESTO ES PORQUE NO LLEVAMOS 
TODO A DIOS EN ORACIÓN. 
 
II 
¿VIVES DÉBIL Y CARGADO 
DE CUIDADOS Y TEMOR? 
A JESÚS, REFUGIO ETERNO 
DDILE TODO EN ORACIÓN. 
¿TE DESPRECIAS TU AMIGOS? 
CUÉNTASELO EN ORACIÓN; 
EN SUS BRAZOS DE AMOR TIERNO 
PAZ TENDRÁ TU CORAZÓN. 
 
III 
JESUCRISTO EN NUESTRO AMIGO, 
DE ESTO PRUEBAS ÉL NOS DIO 
AL SUFRIR EL CRUEL CASTIGO 
QUE EL CULPABLE MERECIÓ. 
Y SU PUEBLO REDIMIDO 
HALLARÁ SEGURIDAD 
FIANDO EN ESTE AMIGO ETERNO 
Y ESPERANDO EN SU BONDAD. 
"""

print("Chunk 1 created")
